mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kuang.pojo
server:
  compression:
    enabled: true
  port: 8301
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/kuangstudy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: postgres
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  thymeleaf:
    cache: false
  web:
    resources:
      add-mappings: false
